services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: profiles
    networks:
      - connections
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - connections
    ports:
      - "6379:6379"
    
  chathub:
    build:
      context: ./MyPlace_Backend
      dockerfile: ChatHub/Dockerfile
    container_name: chathub
    depends_on:
      - redis
    environment:
      - ConnectionStrings__Redis=redis:6379
    networks:
      - connections
    ports:
      - "5023:8080"

  api:
    build:
      context: ./MyPlace_Backend
      dockerfile: MyPlaceAPI/Dockerfile
    container_name: api
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiles;User ID=myuser;Password=mypassword;
    networks:
      - connections
    ports:
      - "5024:8080"
    
  migration:
    build:
      context: ./MyPlace_Backend
      dockerfile: MigrationApplication/Dockerfile
    container_name: migrator
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiles;User ID=myuser;Password=mypassword;
    networks:
      - connections
    ports:
      - "5025:8080"

volumes:
  postgres_data:

networks:
  connections: