apiVersion: batch/v1
kind: Job
metadata:
  name: myplaceapi-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: stran9682/migration:latest
        command: ["dotnet", "ef", "database", "update", "-s", "MyPlaceAPI", "-p", "DataLibrary"]
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: connectionstring
      restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  connectionstring: Ikhvc3Q9cG9zdGdyZXM7UG9ydD01NDMyO0RhdGFiYXNlPXByb2ZpbGVzO1VzZXIgSUQ9bXl1c2VyO1Bhc3N3b3JkPW15cGFzc3dvcmQ7Ig==
