apiVersion: v1
kind: Service
metadata:
  name: minio-cross-ns
spec:
  type: ExternalName
  externalName: minio-nodeport.minio-tenant.svc.cluster.local
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    v1.min.io/tenant: minio-tenant