apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="ROOTNAME"
    export MINIO_ROOT_PASSWORD="CHANGEME123"
    export MINIO_SERVER_URL="155.98.38.240"
    export MINIO_BROWSER_REDIRECT_URL="minio-nodeport:9000"