apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-tenant
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="ROOTNAME"
    export MINIO_ROOT_PASSWORD="CHANGEME123"