apiVersion: apps/v1
kind: Deployment
metadata:
  name: myplaceapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myplaceapi
  template:
    metadata:
      labels:
        app: myplaceapi
    spec:
      initContainers:
      - name: migration-application
        image: stran9682/migrationapplication:latest
        env: 
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connectionstring
        - name: ElasticSettings__Url
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_url
        - name: ElasticSettings__Username
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_username
        - name: ElasticSettings__Password
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_password
        - name: ElasticSettings__DefaultIndex
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_defaultIndex
        - name: ElasticSettings__Fingerprint
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_fingerprint
        
      containers:
      - name: myplaceapi
        image: stran9682/myplaceapi:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connectionstring
        - name: ElasticSettings__Url
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_url
        - name: ElasticSettings__Username
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_username
        - name: ElasticSettings__Password
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_password
        - name: ElasticSettings__DefaultIndex
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_defaultIndex
        - name: ElasticSettings__Fingerprint
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: elastic_fingerprint
---
apiVersion: v1
kind: Service
metadata:
  name: myplaceapi
spec:
  selector:
    app: myplaceapi
  ports:
  - port: 8080
    targetPort: 8080