apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  connectionstring: "Host=postgres-cluster-rw.postgres-system.svc.cluster.local;Port=5432;Database=profiles;User ID=myuser;Password=mypassword;"
  elastic_url: "https://test-cluster-es-http.elastic-system.svc.cluster.local:9200"
  elastic_username: "elastic"
  elastic_password: "fill this in!!!"
  elastic_defaultIndex: "profile_attributes"
  elastic_fingerprint: "fill this in too!!!"