name: API
on:
  push:
    branches:
      - "main"
    paths:
     - 'MyPlace_Backend/MyPlaceAPI/**'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: build & push API image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push API
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: ./MyPlace_Backend
          file: ./MyPlace_Backend/MyPlaceAPI/Dockerfile
          push: true
          tags: stran9682/myplaceapi:latest